version: '2.1'


# depends_on 은 다른 서비스가 정상 동작할때까지 기다린다.
services:
  product:
    build: microservices/product-service
    mem_limit: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      mongodb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy


  recommendation:
    build: microservices/recommendation-service
    mem_limit: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      mongodb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  review:
    build: microservices/review-service
    mem_limit: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  product-composite:
    build: microservices/product-composite-service
    mem_limit: 350m
#  spring cloud gateway 사용시
#    ports:
#      - "8080:8080"
# 아래는 Zuul Test 용
#    ports:
#      - "9080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      rabbitmq:
        condition: service_healthy

  eureka:
    build: spring-cloud/eureka
    mem_limit: 350m
#  spring cloud gateway 사용시
#    ports:
#      - "8761:8761"


  gateway:
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    build: spring-cloud/gateway
    mem_limit: 350m
    ports:
      - "8080:8080"

#  zuulgateway:
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#    build: spring-cloud/zuulgateway
#    mem_limit: 350m
#    ports:
#      - "8081:8081"

  # $ mongo
  mongodb:
    image: mongo:3.6.9
    mem_limit: 350m
    ports:
      - "27017:27017"
    command: mongod --smallfiles
    healthcheck:
      test: "mongo --eval 'db.stats().ok'"
      interval: 10s
      timeout: 5s
      retries: 10

  # $ mysql -uroot -h127.0.0.1 -p
  mysql:
    image: mysql:5.7
    mem_limit: 350m
    ports:
      - "3308:3308"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpwd
      - MYSQL_DATABASE=review-db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pwd
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-uuser", "-ppwd", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

  rabbitmq:
    image: rabbitmq:3.9.4-management
    mem_limit: 350m
    ports:
    - 5672:5672
    - 15672:15672
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 10


  zipkin:
    image: openzipkin/zipkin:2.12.9
    mem_limit: 512m
    environment:
      # 모든 데이터 메모리에
      - STORAGE_TYPE=mem
      - RABBIT_ADDRESSES=rabbitmq
    ports:
      - 9411:9411
    depends_on:
      rabbitmq:
        condition: service_healthy

#  config:
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker,native
#      - ENCRYPT_KEY=${CONFIG_SERVER_ENCRYPT_KEY}
#    volumes:
#      - $PWD/config-repo:/config-repo
#    build: spring-cloud/config
#    mem_limit: 350m

