server:
  port: 8761

# 독립현 유레카 서버의 표준 구성
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  # from: https://github.com/spring-cloud-samples/eureka/blob/master/src/main/resources/application.yml
  server:
    waitTimeInMsWhenSyncEmpty: 0
    #유레카 서버의 시작 시간을 최소화 하기 위한 구성
    response-cache-update-interval-ms: 5000

management.endpoints.web.exposure.include: "*"
spring:
  zipkin:
    sender:
      type: rabbit
      #모든데이터 보냄
  sleuth:
    sampler:
      probability: 1.0
